---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by YangFeng.
--- DateTime: 2023/7/16 16:53
---
---1.参数列表
---1.1 优惠券id
local voucherId = ARGV[1]
---1.2 用户id
local userId = ARGV[2]

---2.数据key
---2.1 库存key
local stockKey = 'seckill:stock:'..voucherId;
---2.2 订单key
local orderKey = 'seckill:order:'..voucherId;

---3.脚本业务
---3.1 判断库存是否充足
if (tonumber(redis.call('get',voucherId)) <= 0) then
    return 1
end
---3.2 判断用户是否下单
if (redis.call('sismemeber', orderKey, userId) == 0) then
    ---3.3 存在，说明是重复下单
    return 2
end
---3.4 不存在，扣减库存: incrby voucherId -1
redis.call('incrby',stockKey,-1)
---3.5 下单：sadd orderKey userId
redis.call('sadd',orderKey,userId)